# Generated by Django 6.0.6 on 2026-06-21 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manage', '0002_alter_task_deadline'),
        ('teams', '0002_alter_teammember_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='teams.team'),
            preserve_default=False,
        ),
    ]
