# Generated by Django 6.0.6 on 2026-07-03 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manage', '0003_task_team'),
        ('teams', '0002_alter_teammember_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='task_manage.category'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to_do', 'Необхідно виконати'), ('in_progress', 'Виконується'), ('done', 'Готове')], max_length=32),
        ),
    ]
