# Generated by Django 6.0.6 on 2026-07-10 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manage', '0004_alter_category_team_alter_task_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
